### ISSUE TITLE
Build fails on archlinux

### ISSUE THREAD

**Issue by maniac-en** [junegunn/blsd#3]
#### System Info
```
$ uname -a
Linux archlinux 5.12.5-arch1-1 #1 SMP PREEMPT Wed, 19 May 2021 10:32:40 +0000 x86_64 GNU/Linux
```

#### Install Command Output
```sh
$ bash <(curl -fL https://raw.githubusercontent.com/junegunn/blsd/master/install)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   207  100   207    0     0    412      0 --:--:-- --:--:-- --:--:--   412
Cloning into '/tmp/blsd'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
Receiving objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0
mkdir -p /tmp/blsd/gopath
go get -d
go: cannot find main module, but found .git/config in /tmp/blsd
        to create a module there, run:
        go mod init
make: *** [Makefile:12: git2go] Error 1
```

### Testing
- I tried building it on an `ubuntu` docker container, it builds successfully.
- I also tried building it on an `archlinux` docker container, but build fails with a similar message as it does on my main machine.

### Issue
Build fails for archlinux (even in the sandboxed env)

Last but not least, thanks for all your OSS contribution. I love fzf, and your vim plugins. If and when you have time, please comment on how to fix this? What's the source of this issue? I'm a `golang` noob.

**Comment by strager** [comment]
Seems to work for me on Manjaro (Arch-based distro) if I set in my environment: `GO111MODULE=auto`

**Comment by maniac-en** [comment]
> Seems to work for me on Manjaro (Arch-based distro) if I set in my environment: `GO111MODULE=auto`

This fixes it for me as well, Thanks :)

I'll keep this open because I think [install](https://github.com/junegunn/blsd/blob/master/install) script should manage this on it's own!

**Comment by junegunn** [comment]
The build script for this project is severely outdated. I probably have to update it to use `go mod`.
But `GO111MODULE=auto` helps for now.

Thanks.
