### ISSUE TITLE
Brew install is not working

### ISSUE THREAD

**Issue by ggsalas** [junegunn/blsd#4]
Hi, I'm trying the command to install with brew: `brew install --HEAD https://raw.githubusercontent.com/junegunn/blsd/master/blsd.rb`

and I get this error: 
``` `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of blsd formula file from an arbitrary URL is unsupported!  (UsageError)```

There is a fox for that? Thanks!

**Comment by junegunn** [comment]
This should work now.

```sh
brew install --HEAD junegunn/tap/blsd
```

**Comment by junegunn** [comment]
Oops, not so fast.
